### ISSUE TITLE
What is it gonna be when its done?

### ISSUE THREAD

**Issue by davvidess** [multiplio/cast-website#18]

**Comment by davvidess** [comment]
Must be serious stuff when bothered buying IO domain 😂

**Comment by tinybeachthor** [comment]
Social media posting service, which aims to separate content from publishers. Content will be stored and distributed worldwide using [IPFS](https://ipfs.io/) (immutable + addressable by hash). While only a [rich link with preview](https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/summary) gets posted to the social media site.

This will allow for better split of responsibilities, as social media should not be responsible for content and should treat it equally, while making the user experience more seamless (single interface for all services) and more open (all content is freely accessible by anyone) - free movement of data, liberating users from service lockdown where data is held hostage by a service.
